package aoc

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

var y2025d7Input = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`

func Test_2025_Day_7_Part_1_Example(t *testing.T) {
	result := y2025d7part1(y2025d7Input)
	assert.Equal(t, "21", result)
}

func Test_2025_Day_7_Part_2_Example(t *testing.T) {
	result := y2025d7part2(y2025d7Input)
	assert.Equal(t, "40", result)
}
